### ISSUE TITLE
Self-dependent tables hang the script

### ISSUE THREAD

**Issue by jorr** [wigy/knex-dump#13]
Hi there,

if we have a table with a relationship to itself (pretty common, e.g. in parent-child relationship), the script hangs, at least on PG, in postgres.js, the loop starting at line 37 never finishes.

I would open PR but it's really just a simple change:

const nonDependents = toSort.filter(t => !constraints.rows.find(c => c.primaryTable === t.name && c.foreignTable !== t.name));

Is it possible to update the lib with that? :)

**Comment by wigy** [comment]
Thanks, added.
